---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - packages/ember-intl/node_modules
    - packages/ember-intl-format-cache/node_modules
    - packages/ember-intl-messageformat/node_modules
    - packages/ember-intl-messageformat-parser/node_modules
    - packages/ember-intl-relativeformat/node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - cd $TRAVIS_BUILD_DIR/packages/ember-intl && npm install && bower install
  - cd $TRAVIS_BUILD_DIR/packages/ember-intl-format-cache && npm install && bower install
  - cd $TRAVIS_BUILD_DIR/packages/ember-intl-messageformat && npm install && bower install
  - cd $TRAVIS_BUILD_DIR/packages/ember-intl-messageformat-parser && npm install && bower install
  - cd $TRAVIS_BUILD_DIR/packages/ember-intl-relativeformat && npm install && bower install

script:
  - cd $TRAVIS_BUILD_DIR/packages/ember-intl && npm run tests-node
  - cd $TRAVIS_BUILD_DIR/packages/ember-intl && ember try $EMBER_TRY_SCENARIO test
  - cd $TRAVIS_BUILD_DIR/packages/ember-intl-format-cache && ember try $EMBER_TRY_SCENARIO test
  - cd $TRAVIS_BUILD_DIR/packages/ember-intl-messageformat && ember try $EMBER_TRY_SCENARIO test
  - cd $TRAVIS_BUILD_DIR/packages/ember-intl-messageformat-parser && ember try $EMBER_TRY_SCENARIO test
  - cd $TRAVIS_BUILD_DIR/packages/ember-intl-relativeformat && ember try $EMBER_TRY_SCENARIO test
